export const SKILLS: Record<string, string[]> = {
  "Core Languages": ["JavaScript (ES6+)", "TypeScript", "HTML5", "CSS3", "Sass"],
  "Frontend Frameworks": [
    "React.js",
    "Next.js (SSR / ISR / App Router)",
    "React Router",
    "React Hooks",
    "Custom Hooks",
  ],
  "State Management": [
    "Redux",
    "Redux Toolkit",
    "Context API",
    "React Query (TanStack)",
  ],
  Styling: [
    "Tailwind CSS",
    "Sass/SCSS",
    "Styled Components",
    "Material UI",
    "Next UI",
    "Figma",
    "Design Systems",
  ],
  "Forms & Validation": ["React Hook Form", "Formik", "Zod", "Yup"],
  "Backend Familiarity": [
    "Node.js",
    "NestJS",
    "REST API Design",
    "Server-Sent Events (SSE)",
    "WebSockets",
    "JWT / RBAC",
  ],
  Testing: [
    "Jest",
    "React Testing Library",
    "Unit Testing",
    "Integration Testing",
  ],
  Performance: [
    "Code Splitting",
    "Lazy Loading",
    "Memoization",
    "Web Performance Optimization",
    "SLO/SLA Principles",
  ],
  "DevOps & Tooling": [
    "Git",
    "GitHub",
    "GitLab",
    "Docker",
    "Webpack",
    "Vite",
    "GitHub Actions",
    "Vercel",
    "AWS",
    "Postman",
    "Jira",
    "ESLint",
    "Prettier",
    "npm",
    "Yarn",
    "pnpm",
  ],
  Practices: [
    "Clean Code",
    "Component Reusability",
    "Component-Driven Design",
    "Multi-Tenancy",
    "Code Review",
    "Agile/Scrum",
    "CI/CD Basics",
    "Accessibility (a11y)",
  ],
};
